/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#bd5444',
        'surface-dim': '#ded9d2',
        'surface-container-high': '#ece8e0',
        'surface-variant': '#e7e2da',
        'primary-fixed-dim': '#ffb4a7',
        'error': '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#c1cc99',
        'on-tertiary-fixed-variant': '#5e4200',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#ffdad4',
        'surface-bright': '#fef9f1',
        'inverse-on-surface': '#f5f0e8',
        'on-primary-fixed-variant': '#80281b',
        'tertiary-fixed-dim': '#f4be55',
        'inverse-surface': '#32302b',
        'outline': '#89726d',
        'surface-container': '#f2ede5',
        'secondary-container': '#dde8b3',
        'inverse-primary': '#ffb4a7',
        'tertiary-fixed': '#ffdea7',
        'on-surface-variant': '#56423e',
        'surface-container-highest': '#e7e2da',
        'on-secondary-fixed-variant': '#414b23',
        'on-primary': '#ffffff',
        'surface': '#fef9f1',
        'secondary': '#596339',
        'on-primary-fixed': '#400200',
        'secondary-fixed': '#dde8b3',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#271900',
        'on-surface': '#1d1c17',
        'on-secondary': '#ffffff',
        'outline-variant': '#ddc0bb',
        'tertiary-container': '#9b6f01',
        'background': '#fef9f1',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#171e00',
        'on-primary-container': '#fffbff',
        'on-tertiary-container': '#080400',
        'on-secondary-container': '#5f693e',
        'surface-tint': '#a03f30',
        'primary': '#9d3d2e',
        'tertiary': '#7c5800',
        'surface-container-low': '#f8f3eb',
        'on-background': '#1d1c17',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
